name: "Build Installers"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ubuntu version of the runner'
        required: true
        default: 'noble'
        type: choice
        options:
          - jammy
          - noble

      arch:
        description: 'Architecture of the runner'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64

  pull_request:
    branches:
      - main

  push:
    branches:
      - test_gh_runner

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "changed=$files" >> $GITHUB_OUTPUT

  manual-build:
    if: github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        test_name: [vulkan, opencl, crucible, opengl]
    name: "Manual Build - ${{ matrix.test_name }}"
    runs-on: [self-hosted, linux, "${{ inputs.arch }}", "${{ inputs.version }}"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run install-${{ matrix.test_name }}
        shell: bash
        run: bin/install-${{ matrix.test_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "output-${{ matrix.test_name }}-\
          ${{ inputs.arch }}-${{ inputs.version }}"
          path: /usr/local/checkbox-gfx/*

  pr-build:
    needs: detect-changes
    if: >
      (github.event_name == 'pull_request' ||
      github.event_name == 'push') &&
      contains(needs.detect-changes.outputs.changed,
        format('bin/install-{0}', matrix.test_name))
    strategy:
      matrix:
        arch: [amd64, arm64]
        test_name: [vulkan, opencl, crucible, opengl]
    name: "Installer testing"
    runs-on: [self-hosted, linux, "${{ matrix.arch }}", noble]

    steps:
      - name: "Installers - ${{ matrix.test_name }} - ${{ matrix.arch }}"
        run: echo "Running ${{ matrix.test_name }} ${{ matrix.arch }} install"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run install-${{ matrix.test_name }}
        shell: bash
        run: bin/install-${{ matrix.test_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.test_name }}-${{ matrix.arch }}
          path: /usr/local/checkbox-gfx/*
