name: "Build Crucible"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ubuntu version of the runner'
        required: true
        default: 'noble'
        type: choice
        options:
          - jammy
          - noble

      arch:
        description: 'Architecture of the runner'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - ARM64
    push:
      branches:
      - test_gh_runner
    paths:
      - bin/install-crucible
    pull_request:
      branches:
      - main
      paths:
      - bin/install-crucible

jobs:
  run-install-crucible:
    name: "Run install-crucible to generate Mesa testing binaries"
    runs-on: [ self-hosted, linux, "${{ inputs.arch }}", "${{ inputs.version}}" ]

    steps:
      - name: checkout the main repo
        uses: actions/checkout@v4

      - name: Run install-crucible
        shell: bash
        run: |
          bin/install-crucible

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            /usr/local/checkbox-gfx/*
